M48
; DRILL file {KiCad 7.0.8} date 2023 October 16, Monday 07:21:47
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-16T07:21:47+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X100.0Y-100.0
X100.0Y-125.0
X230.0Y-100.0
X230.0Y-125.0
T0
M30
